"""Coverage for the dispatch-surface PAT guard test helpers."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from types import ModuleType

import pytest

_REPO_ROOT = Path(__file__).resolve().parents[1]
_GUARD_TEST_PATH = _REPO_ROOT / "tests" / "test_fleet_pat_dispatch_surface.py"
_MODULE_NAME = "fleet_pat_dispatch_surface_under_test"
# A byte sequence NO UTF-8 decoder accepts: 0x8e at offset 8 is a continuation
# byte with no lead byte in front of it. These are the leading bytes of a real
# CPython 3.10 `.pyc` header, so this fixture reproduces the exact input that
# raised `UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position
# 8` whenever an earlier pytest-xdist worker had compiled the scanned package
# before this guard ran (work-item bd-ib-2fsy).
_NON_UTF8_BYTES = b"o\r\r\n\x00\x00\x00\x00\x8e\xc3\xc3j\xe0\x0c\x00\x00"


def _load_guard_test() -> ModuleType:
    spec = importlib.util.spec_from_file_location(_MODULE_NAME, _GUARD_TEST_PATH)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[_MODULE_NAME] = module
    spec.loader.exec_module(module)
    return module


def test_surface_files_includes_files_directories_and_ignores_missing_paths(
    tmp_path: Path,
) -> None:
    guard_test = _load_guard_test()
    direct_file = tmp_path / "direct.txt"
    direct_file.write_text("safe", encoding="utf-8")
    nested = tmp_path / "surface" / "nested.txt"
    nested.parent.mkdir()
    nested.write_text("safe", encoding="utf-8")

    guard_test._REPO_ROOT = tmp_path  # noqa: SLF001
    guard_test._DISPATCH_SURFACES = (  # noqa: SLF001
        Path("direct.txt"),
        Path("surface"),
        Path("missing"),
    )

    assert guard_test._surface_files() == [direct_file, nested]  # noqa: SLF001
    guard_test.test_dispatch_surfaces_do_not_reference_the_retired_fleet_pat()


def test_the_guard_scans_a_surface_holding_generated_bytecode_and_binary_files(
    tmp_path: Path,
) -> None:
    """Generated bytecode and non-UTF-8 binaries must not abort the scan.

    The regression control for bd-ib-2fsy: the scan fed every regular
    file to `read_text(encoding="utf-8")`, so a single `__pycache__/*.pyc`
    left behind by an earlier pytest-xdist worker raised
    `UnicodeDecodeError` and the guard failed for a reason that had
    nothing to do with the token it guards.

    Two separate properties are asserted, because a fix for either one
    alone leaves the other broken. Generated bytecode is dropped from the
    scanned set outright — it is an untracked by-product, not a dispatch
    surface, and whether it was present at all depended on worker
    ordering. A non-UTF-8 file that is NOT bytecode stays IN the scanned
    set and is read as bytes, so no binary a dispatch surface may
    legitimately carry can ever abort the scan. The extensionless file
    proves the exclusion is keyed on the `__pycache__` directory rather
    than on an allow-list of text suffixes, which a file with no suffix
    could never satisfy.
    """
    guard_test = _load_guard_test()
    surface = tmp_path / "surface"
    bytecode = surface / "__pycache__" / "module.cpython-310.pyc"
    bytecode.parent.mkdir(parents=True)
    bytecode.write_bytes(_NON_UTF8_BYTES)
    binary = surface / "payload.bin"
    binary.write_bytes(_NON_UTF8_BYTES)
    extensionless = surface / "entrypoint"
    extensionless.write_text("export GITHUB_TOKEN=app\n", encoding="utf-8")

    guard_test._REPO_ROOT = tmp_path  # noqa: SLF001
    guard_test._DISPATCH_SURFACES = (Path("surface"),)  # noqa: SLF001

    assert guard_test._surface_files() == [extensionless, binary]  # noqa: SLF001
    guard_test.test_dispatch_surfaces_do_not_reference_the_retired_fleet_pat()


def test_the_guard_failure_names_the_text_file_holding_the_retired_token(
    tmp_path: Path,
) -> None:
    """A real occurrence still fails the guard, and the failure NAMES the file.

    The positive control to the regression control above: a scan that
    cannot crash is worthless if it also cannot report. Generated
    bytecode sits on the surface here too, so this asserts the reporting
    path across the same input that used to abort the scan.

    The failure message is read rather than inferred because this module
    loads the guard through `importlib`, which bypasses pytest's
    assertion rewriting — so the guard must carry its own message or the
    `AssertionError` reaches an operator empty.
    """
    guard_test = _load_guard_test()
    surface = tmp_path / "surface"
    bytecode = surface / "__pycache__" / "module.cpython-310.pyc"
    bytecode.parent.mkdir(parents=True)
    bytecode.write_bytes(_NON_UTF8_BYTES)
    offender = surface / "dispatch.sh"
    offender.write_text(f"export {guard_test._TOKEN}=secret\n", encoding="utf-8")  # noqa: SLF001

    guard_test._REPO_ROOT = tmp_path  # noqa: SLF001
    guard_test._DISPATCH_SURFACES = (Path("surface"),)  # noqa: SLF001

    with pytest.raises(AssertionError) as failure:
        guard_test.test_dispatch_surfaces_do_not_reference_the_retired_fleet_pat()

    assert "surface/dispatch.sh" in str(failure.value)
