"""Tree-wide guard for retired fleet PAT references in dispatch surfaces."""

from __future__ import annotations

from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]
_TOKEN = "LIVESPEC_FAMILY_GITHUB_TOKEN"
_TOKEN_BYTES = _TOKEN.encode("ascii")
_GENERATED_BYTECODE_DIR = "__pycache__"
_DISPATCH_SURFACES = (
    Path("orchestrator-image"),
    Path(".claude-plugin/scripts"),
    Path(".claude-plugin/.fabro"),
    Path(".github/workflows"),
)


def _surface_files() -> list[Path]:
    """Every regular file on the dispatch surfaces, generated bytecode aside.

    `__pycache__` is dropped because generated bytecode is not a dispatch
    surface: it is an untracked by-product of importing the package under
    `.claude-plugin/scripts`, so whether this scan saw any at all depended
    on which pytest-xdist worker imported that package first (work-item
    bd-ib-2fsy). Its content is also derived — a `.pyc` can only carry the
    token if the `.py` beside it does, and that `.py` is scanned.

    The exclusion is keyed on the DIRECTORY NAME rather than on an
    allow-list of text suffixes, because the surfaces carry extensionless
    text — container entrypoints and hook scripts — which no suffix
    allow-list could admit.
    """
    files: list[Path] = []
    for surface in _DISPATCH_SURFACES:
        root = _REPO_ROOT / surface
        if root.is_file():
            files.append(root)
        elif root.is_dir():
            files.extend(
                path
                for path in root.rglob("*")
                if path.is_file() and _GENERATED_BYTECODE_DIR not in path.parts
            )
    return sorted(files)


def _token_hits() -> list[str]:
    """Scanned files carrying the retired token, as repo-relative posix paths.

    The match is on BYTES. A dispatch surface may legitimately hold a file
    that is not UTF-8 text — an image, an archive, a stray compiled
    artifact — and `Path.read_text` raises `UnicodeDecodeError` on one,
    which ABORTS the scan instead of reporting a finding: the guard then
    fails for a reason that has nothing to do with the token it guards.
    Searching for the token's ASCII bytes cannot raise on any byte
    sequence, so every file stays scannable and only a real occurrence
    fails the guard.

    Excluding `__pycache__` in `_surface_files` is therefore not the whole
    repair, and neither half substitutes for the other: the exclusion
    removes the one binary the suite itself generates, and byte-matching
    removes the whole failure MODE, including for a binary no one
    anticipated.
    """
    return [
        path.relative_to(_REPO_ROOT).as_posix()
        for path in _surface_files()
        if _TOKEN_BYTES in path.read_bytes()
    ]


def test_dispatch_surfaces_do_not_reference_the_retired_fleet_pat() -> None:
    hits = _token_hits()
    # The message is explicit rather than left to pytest's assertion
    # rewriting: `test_fleet_pat_dispatch_surface_helpers.py` exercises this
    # guard through `importlib`, which bypasses rewriting, so a bare
    # comparison would reach that caller — and any other direct caller — as
    # an `AssertionError` with no text at all.
    assert not hits, f"retired fleet PAT env name {_TOKEN} found in dispatch surface(s): {hits}"
